application: email-processor-sample
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- mail

handlers:
- url: /css
  static_dir: css

- url: /_ah/mail/.+
  script: handle_email.app
  login: admin

- url: /.*
  script: email_processor.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
